from src.exception import *

class custom_exception(Exception):
    pass
